services:
  postgres:
    container_name: todos_postgres
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todos
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  fastapi:
    container_name: todos_fastapi
    build:
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    ports:
      - "3001:3001"
    restart: always
    depends_on:
      - postgres
